server:
  address: "127.0.0.1"
  port: 2333

lavalink:
  server:
    password: "${LAVALINK_PASSWORD:youshallnotpass}"
    sources:
      youtube: true
      soundcloud: true
      twitch: true
      bandcamp: true
      http: true
      local: true
    plugins:
      - lapix: true
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    gcWarnings: true
    playlistFetchLimit: 10
    playlistSearchLimit: 10
    playlistSearchRelevanceFilterLimit: 100

  plugins:
    - name: youtube-source
      class: dev.lavalink.youtube.YoutubeSourceManager
      enabled: true
    - name: lavarsc
      class: dev.lavalink.LavaSrc.LavaSrcManager
      enabled: true
      spotify:
        client-id: "${SPOTIFY_CLIENT_ID:}"
        client-secret: "${SPOTIFY_CLIENT_SECRET:}"

  tracking:
    client: lavalink4j
    interval: 10